config/routes.rb
Rails.application.routes.draw do
  root to: "products#index"

  resources :user_sessions, only: [:new, :create, :destroy]
  resources :products, only: [:index] do
    post "archive", on: :member
  end

  get  "login"  => "user_sessions#new",     as: :login
  post "logout" => "user_sessions#destroy", as: :logout
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    if user.new_record?
      can :read, Product, status: Product.statuses[:active]
    elsif user.employee?
      can [:read, :update], Product
    elsif user.management?
      can [:read, :update, :archive], Product
    elsif user.admin?
      can :manage, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  enum status: {
    active: 0,
    archived: 10
  }

  scope :updated_by_employee, -> do
    joins(
      <<~SQL
        INNER JOIN users ON users.id = products.updated_by
        AND users.role = #{User.roles[:employee]}
      SQL
    )
  end

  scope :updated_during_last_week, -> do
    last_week = 1.week.ago.to_date..1.day.ago.to_date
    where(updated_at: last_week)
  end

  scope :updated_by_employee_last_week, -> do
    updated_by_employee.updated_during_last_week.order(:updated_at)
  end

  def name
    "#{title.titleize} ##{articul.upcase}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  enum role: {
    employee: 0,
    management: 10,
    admin: 20
  }

  scope :management_average_age, -> { management.average(:age).to_f }
  scope :non_admins,             -> { where.not(role: :admin) }
  scope :oldest_users,           -> { non_admins.order(age: :desc).limit(3) }

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :require_login

  private

  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :require_login, only: [:index]
  load_and_authorize_resource

  def index
    @products = params[:updated_by_employee_last_week] ? Product.updated_by_employee_last_week
                                                       : Product.all.order(:updated_at)
  end

  def archive
    @product.active? ? @product.archived!
                     : @product.active!
    redirect_back(fallback_location: root_path, notice: "Product archived successfully")
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(root_path, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(root_path, notice: 'Logged out!')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def price_with_sale(product)
    unless product.sale.zero?
      product.price *= 2
      css_class = "sale"
    end

    content_tag(:span, number_to_currency(product.price), class: css_class)
  end

  def modifier_link(product)
    if user = User.find_by(id: product.updated_by)
      link_to(user.full_name, "#")
    end
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Elixir test
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    #nav
      - if current_user
        = link_to "Logout", :logout, method: :post
      - else
        = link_to "Login", :login
    %div
      %p#notice= flash[:notice]
      %p#alert= flash[:alert]
    = yield

app/views/products/_product.html.haml
- if can? :read, product
  %tr{:class => "product #{product.status}"}
    %td= product.name
    %td= price_with_sale(product)
    %td
      - unless product.sale.zero?
        Sale
    %td
      - if can? :update, Product
        = link_to "Edit", "#"
      - if can? :archive, Product
        = link_to("Archive", archive_product_path(product), method: :post)
    - if can? :manage, Product
      %td= modifier_link(product)

app/views/products/index.html.haml
%h1 Products

.products
  - if can? :manage, Product
    %ul
      %li= link_to "All products (A-Z)", root_path
      %li= link_to "Show products updated by employees last week", root_path(updated_by_employee_last_week: true)

  %table
    %tr
      %th Name
      %th Price
      %th With Sale
      - if current_user
        %th Actions
      - if can? :manage, Product
        %th Updated By
    = render @products

app/views/user_sessions/_form.html.haml
= form_tag user_sessions_path, :method => :post do
  .field
    = label_tag :email
    %br/
    = text_field_tag :email
  .field
    = label_tag :password
    %br/
    = password_field_tag :password
  .actions
    = submit_tag "Login"

app/views/user_sessions/new.html.haml
%h1 Login
= render 'form'
= link_to 'Back', user_sessions_path